DjangoSite/DjangoSite/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('about.urls')),
    path('', include('sintactico.urls')),
    path('', include('grafo.urls')),
]

DjangoSite/about/urls.py
from django.urls import path
from .views import about

app_name = 'about'

urlpatterns = [
    path("about/", about, name="about")
]

DjangoSite/grafo/urls.py
from django.urls import path
from .views import grafo

app_name = 'grafo'

urlpatterns = [
    path("grafo/", grafo, name="grafo"),
]

DjangoSite/home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    
]

DjangoSite/sintactico/urls.py
from django.urls import path
from .views import sintactico

#app_name = AppName

urlpatterns = [
    path("sintactico/", sintactico, name="sintactico")
]

DjangoSite/about/models.py
from django.db import models

# Create your models here.

DjangoSite/grafo/models.py
from django.db import models

# Create your models here.
class Distance(models.Model):

    R1 = models.IntegerField()
    R2 = models.IntegerField()
    distance = models.FloatField()

    class Meta:
        verbose_name = ("Distance")
        verbose_name_plural = ("Distances")

    def __str__(self):
        return self.distance

    def get_absolute_url(self):
        return reverse("Distance_detail", kwargs={"pk": self.pk})

DjangoSite/home/models.py
from django.db import models
class Paciente(models.Model):
    name = models.CharField(max_length=50)


    class Meta:
        verbose_name = "Paciente"
        verbose_name_plural = "Pacientes"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Paciente_detail", kwargs={"pk": self.pk})

# Create your models here.
class Tessiu(models.Model):
    temperatura = models.FloatField()
    color = models.FloatField()
    inflammation = models.FloatField(verbose_name='inflamación')
    name = models.ForeignKey(Paciente, blank=True, null=True, verbose_name='nombre',on_delete=models.CASCADE)
    #FIELDNAME = models.ManyToManyField(OTHERMODEL)
    #fieldname = models.OneToOneField("app.Model", verbose_name=_(""), on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Tejido")
        verbose_name_plural = ("Tejidos")

    def __str__(self):
        if self.name is not None:
            return str(self.temperatura)
        else:
            return str(self.temperatura)

    def get_absolute_url(self):
        return reverse("Tejido_detail", kwargs={"pk": self.pk})
        

DjangoSite/sintactico/models.py
from django.db import models

# Create your models here.

DjangoSite/grafo/forms.py
from django import forms
from django.forms.fields import IntegerField
from django.shortcuts import render
from .models import Distance

class Beta(forms.Form):
    Ingresa = forms.IntegerField(required=False)
    

DjangoSite/about/views.py
from django.shortcuts import render

# Create your views here.



def about(request):
    template_name="about/about.html"
    nombre=consultaDB(request)

    lista = [1,2,3,4,5]

    return render(request, template_name, {'nombre':nombre, 'apellido':"Rivera", 'milista':lista})


def consultaDB(request):
    return "Nightmare"

DjangoSite/grafo/views.py
from django.shortcuts import render
from .models import Distance
from .forms import Beta

# Create your views here.
def grafo(request):
    template_name = "grafo/grafo.html"
    form = Beta(request.POST)
    if form.is_valid():
        umbral = form.cleaned_data['Ingresa']
        form = Beta()
    L=Distance.objects.get_queryset()
    diccionario = {'umbral':umbral, 'form':form, 'lista':L}
    return render(request, template_name, diccionario)

""" def arreglo(lista):
    row=[]
    for i in lista:
        col=[]
        for j in lista:
            suma=0
            suma=suma+((i.temperatura-j.temperatura)**2)+((i.color-j.color)**2)+((i.inflammation-j.inflammation)**2)
            dist=suma**0.5
            col.append(dist)
        row.append(col)
    return row """

DjangoSite/home/views.py
from django.shortcuts import render
from .models import Tessiu

# Create your views here.
def home(request):
    L=Tessiu.objects.get_queryset()
    template_name = "home/index.html"
    diccionario = {'lista':L}
    return render(request, template_name, diccionario)

DjangoSite/sintactico/views.py
from django.shortcuts import render
from home.models import Tessiu

# Create your views here.
def sintactico (request):
    L=Tessiu.objects.get_queryset()
    template_name = "sintactico/sintactico.html"
    diccionario = {'lista':L}
    return render(request, template_name, diccionario)
    

DjangoSite/about/templates/about/about.html
{% extends 'home/index.html' %} {% block contenido %}


<h1 style="text-align: center;">Sobre nosotros</h1>
<p style="text-align: justify;">
    El cancer de prostata no es un juego, hay que romper los tabues e ir a realizarse las pruebas pertinenetes cuando sea la hora. Si no cuidamos de nosotros mismos entonces quien lo hara.
    <br><br>¿Necesitas ayuda profesional?:
    <ul>
        <li>
            Fundacion de Alba:
            <ul>
                <li>
                    <img src="https://w7.pngwing.com/pngs/428/279/png-transparent-computer-icons-web-page-identity-angle-text-logo.png" width="25" height="25" style="border-radius: 25px;"></a>
                    <a href="http://www.queondacontushuevos.com/">http://www.queondacontushuevos.com/</a>
                </li>
                <li>
                    <img src="https://w7.pngwing.com/pngs/662/783/png-transparent-facebook-inc-social-media-computer-icons-social-network-facebook-blue-text-trademark.png" width="25" height="25" style="border-radius: 25px;"></a>
                    <a href="https://www.facebook.com/queondacontushuevos">¿Que onda con tus huevos?</a>
                </li>
                <li>
                    <img src="https://e7.pngegg.com/pngimages/708/311/png-clipart-twitter-twitter-thumbnail.png" width="25" height="25" style="border-radius: 25px;"></a>
                    <a href="https://twitter.com/ondadehuevos">@OndadeHuevos</a>
                </li>
            </ul>
        </li>
        <li>
            Asociación Mexicana de Lucha Contra el Cancer A.C.:
            <ul>
                <li>
                    <img src="http://assets.stickpng.com/images/5a4525f5546ddca7e1fcbc86.png" width="25" height="25" style="border-radius: 25px;"></a>
                    <a href="tel:555574 0393">(55) 5574 - 0393</a> o
                    <a href="tel:5555640794">(55) 5564 - 0794</a>
                </li>
                <li>
                    <img src="http://assets.stickpng.com/images/5a4525f5546ddca7e1fcbc86.png" width="25" height="25" style="border-radius: 25px;"></a>
                    <a href="tel:5555740393">(55) 5574 - 0393</a>
                </li>
                <li>
                    <img src="https://w7.pngwing.com/pngs/1023/729/png-transparent-email-address-electronic-mailing-list-logo-internet-email-miscellaneous-angle-triangle.png" width="25" height="25" style="border-radius: 25px;"></a>
                    <a href="mailto:contacto@amlcc.org">contacto@amlcc.org</a>
                </li>
            </ul>
        </li>
        <li>
            Instituto Mexicano del Seguro Socail (IMSS):
            <ul>
                <li>
                    <img src="https://w7.pngwing.com/pngs/662/783/png-transparent-facebook-inc-social-media-computer-icons-social-network-facebook-blue-text-trademark.png" width="25" height="25" style="border-radius: 25px;"></a>
                    <a href="https://www.facebook.com/gobmexico">facebook.com/gobmexico</li>
                <li>
                    <img src="https://e7.pngegg.com/pngimages/708/311/png-clipart-twitter-twitter-thumbnail.png" width="25" height="25" style="border-radius: 25px;"></a>
                    <a href="https://twitter.com/GobiernoMX">twitter.com/GobiernoMX</a>
                </li>
            </ul>
        </li>
    </ul>
</p>
{% endblock contenido %}

DjangoSite/grafo/templates/grafo/grafo.html
{% extends 'home/index.html' %} {% block contenido %}

<h1 style="text-align: center;">Checalo tu mismo</h1>

<p style="text-align: justify;">
    Todos los hombres deben ir a consulta periódica, realizarse estudios, sobre todo no tener miedo a padecer alguna enfermedad. Tiene que dejar atrás miedos, mitos y tabúes para vivir bien y mejor.
</p>
<center>
    <form action="{% url 'grafo:grafo' %} " method="post">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit " name="in" style="background-color: forestgreen; border: 2px solid black; border-radius: 10px; width: 75px; height: 30px; font-size: 15px; font-weight: bold; font-family: Comic Sans MS,Arial,Verdana;">Procesar</button>
        <br><br>
    </form>

    {% if umbral %}

    <table style="border: 1px solid black;">
        <thead>
            <tr>
                <th style="border: 1px solid black; ">R1</th>
                <th style="border: 1px solid black; ">R2</th>
                <th style="border: 1px solid black; ">Distancia</th>
                <th style="border: 1px solid black; ">Si/No</th>
            </tr>
        </thead>
        <tbody>
            {% for elemento in lista %}
            <tr>
                <td style="border: 1px solid black; ">{{elemento.R1}}</td>
                <td style="border: 1px solid black; ">{{elemento.R2}}</td>
                <td style="border: 1px solid black; ">{{elemento.distance}}</td>

                {% if elemento.distance > umbral %}
                <td style="border: 1px solid black; ">NO</td>
                {% else %}
                <td style="border: 1px solid black; ">SI</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</center>
{% endif %} {% endblock contenido %}

DjangoSite/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RPSE Matutino</title>
</head>

<body bgcolor="skyblue" text="blue" link="green" alink="red" vlink="blue" style="font-family: Comic Sans MS,Arial,Verdana;">
    <header>
        <center>
            <table style="border: 1px solid skyblue;">
                <tbody>
                    <tr>
                        <th><img src="https://laverdad.com.mx/wp-content/uploads/2021/11/89005494-noviembre-mes-de-lucha-contra-el-cancer-de-prostata-en-espanol.jpg" width="150" height="150"></th>
                        <th style="width: 100px;"></th>
                        <th style="font-size: 55px;">Noviembre mes del cancer de prostata
                            <p style="font-size: 20px;">"El rosa ya no es exclusivo de las mujeres, el cancer tampoco"</p>
                        </th>
                    </tr>
                </tbody>
            </table>
            <hr style="border: 1px solid black;">
            <nav>
                <table style="border: 1px solid skyblue;">
                    <tbody>
                        <tr>
                            <th style="width: 150px;">
                                <form action="{% url 'home:home'%}">
                                    {% csrf_token %}
                                    <button style="background-color: cyan; border: 2px solid black; border-radius: 25px; width: 100px; height: 50px; font-size: 25px; font-weight: bold; font-family: Comic Sans MS,Arial,Verdana;">Home</button>
                                </form>
                            </th>
                            <th style="width: 150px;">
                                <form action="{% url 'sintactico'%}">
                                    {% csrf_token %}
                                    <button style="background-color: cyan; border: 2px solid black; border-radius: 25px; width: 100px; height: 50px; font-size: 25px; font-weight: bold; font-family: Comic Sans MS,Arial,Verdana;">Info</button>
                                </form>
                            </th>
                            <th style="width: 150px;">
                                <form action="{% url 'grafo:grafo'%}">
                                    {% csrf_token %}
                                    <button style="background-color: cyan; border: 2px solid black; border-radius: 25px; width: 100px; height: 50px; font-size: 25px; font-weight: bold; font-family: Comic Sans MS,Arial,Verdana;">Check</button>
                                </form>
                            </th>
                            <th style="width: 150px;">
                                <form action="{% url 'about:about'%}">
                                    {% csrf_token %}
                                    <button style="background-color: cyan; border: 2px solid black; border-radius: 25px; width: 100px; height: 50px; font-size: 25px; font-weight: bold; font-family: Comic Sans MS,Arial,Verdana;">About</button>
                                </form>
                            </th>
                        </tr>
                    </tbody>
                </table>
            </nav>
        </center>
    </header>

    <hr style="border: 1px solid black; ">

    <main>
        {% block contenido %}
        <h1 style="text-align: center;">
            ¡ BIENVENIDO !
        </h1>
        <p style="text-align: justify;">
            Después del “mes rosa”, dedicado a la salud femenina, y en el que se aborda específicamente el tema del cáncer de mama, entramos de lleno al mes de noviembre, o “mes azul” dedicado a la salud masculina, cuyo objetivo principal es el de impulsar en los
            varones adultos la adopción de una visión preventiva de la medicina.
            <br><br>Desde el inicio de este mes, a nivel mundial está en curso la campaña Noviembre Azul. Si el mes de octubre fue rosa y dedicado a la concientización al respecto del diagnóstico y tratamiento del cáncer de mama, ahora, el mes es azul
            y el enfoque es la prevención al cáncer de próstata. La primera iniciativa de Noviembre Azul inició en Australia, en 2003, y se volvió mundialmente conocida como Movember, fusión de las palabras moustache (bigotes) y november (noviembre).
            Este mes también fue escogido porque el día 17 se conmemora el Día Mundial de la Lucha Contra el Cáncer de Próstata.
            <br><br> En muchas ocasiones se ha hablado acerca de la enorme importancia que tiene detectar, diagnosticar y ofrecer de manera temprana y expedita, el o los tratamientos necesarios que ayuden a evitar el desarrollo, complicación o agravamiento
            de las enfermedades, en este caso las que aquejan con mayor frecuencia a los hombres en México, y entre las que destacan las afecciones cardiovasculares (primariamente hipertensión arterial); los cánceres de próstata (primera causa de mortalidad
            por cáncer en los hombres mexicanos), testículos y colon; orquitis, orquiepididimitis; disfunción eréctil y diabetes, constituida esta última como la primera causa de muerte entre las mujeres y la segunda entre los hombres, e importante factor
            de riesgo para el desarrollo de cardiopatías y accidentes cerebrovasculares.
            <br><br> De acuerdo con la opinión del Dr. Omar Hernández León, jefe del servicio de Urología del Hospital Juárez de México, es necesario que a partir de los 40 años de edad los hombres acudan regularmente a consulta médica, para que el especialista
            de la salud tenga oportunidad de evaluar, entre otras cosas, sus niveles de colesterol, triglicéridos y glucosa en sangre, la función hepática, la presión arterial, y peso corporal.
            <br><br>Por ello se invita a todos los varones mayores de 40 años a vencer la resistencia, enfrentar al miedo e ignorar los tabúes para acudir al médico de manera preventiva.
        </p>
        <center>
            <img src="https://codigof.mx/wp-content/uploads/2020/11/NoviembreMesAzul.jpg" width="600" height="300">
        </center>
        {% endblock contenido %}
    </main>
</body>

</html>

DjangoSite/sintactico/templates/sintactico/sintactico.html
{% extends 'home/index.html' %} {% block contenido %}
<h1 style="text-align: center;">Info</h1>
<table>
    <tbody>
        <tr>
            <th>
                <table style="border: 1px solid black;">
                    <thead>
                        <tr>
                            <th style="border: 1px solid black; ">Clave</th>
                            <th style="border: 1px solid black; ">Temperatura</th>
                            <th style="border: 1px solid black; ">Color</th>
                            <th style="border: 1px solid black; ">Informacion</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for elemento in lista %}
                        <tr>
                            <td style="border: 1px solid black; ">{{elemento.pk}}</td>

                            {% if elemento.temperatura > 50 %}
                            <td style="border: 1px solid red; ">{{elemento.temperatura}}</td>
                            {% else %}
                            <td style="border: 1px solid black; ">{{elemento.temperatura}}</td>
                            {% endif %}
                            <td style="border: 1px solid black; ">{{elemento.color}}</td>
                            <td style="border: 1px solid black; ">{{elemento.inflammation}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </th>
            <th style="width: 50px;"></th>
            <th style="vertical-align: text-top;">
                <p style="text-align: justify;">
                    La próstata es una glándula ubicada debajo de la vejiga y delante del recto, del tamaño de una nuez, que solo la poseen los hombres. Su función es producir una parte del líquido simiente (semen). La enfermedad tiene como factor principal la aparición
                    de células malignas o cancerosas en los tejidos de la próstata. Sin embargo, no existen síntomas, hasta tanto se encuentra en estado avanzado. La mortalidad es ocasionada, principalmente, porque el cáncer es detectado en su etapa conocida
                    como de metástasis o no curable.
                    <br><br>De acuerdo con Francisco Varela Riojano, subjefe del servicio de Oncología del Hospital Juárez de México, el 70% de los casos se detecta en etapas avanzadas. Y según la Comisión Nacional para los Derechos Humanos (CNDH), el
                    cáncer de próstata es el causante de 14 muertes diarias de mexicanos.
                    <br><br>Entre los tumores malignos, es la primera causa principal de muerte por cáncer y es la más común en todo el mundo, seguido solamente por el cáncer de pulmón. Y, anualmente, se registran alrededor de 12 500 casos nuevos de cáncer
                    de próstata.
                    <br><br>El cáncer de próstata es silencioso y exige prevención. Una de las formas para verificar la existencia de la enfermedad es por medio de la prueba PSA (Antígeno Prostático Específico). A pesar de que no es específicamente para
                    la detección del cáncer, sino para la evaluación de la próstata (que puede aumentar de tamaño por diversos factores, como una inflamación o la edad, por ejemplo), su resultado puede ser una señal de la enfermedad. Otro examen que no
                    sustituye al anterior es el de tacto rectal. En caso de historial familiar, cuando el padre, el hermano o el tío ya tuvieron cáncer de próstata, lo ideal es empezar a hacerlo a los 40 años. En caso de que no haya incidencia familiar,
                    el examen debe realizarse a los 45 años.
                    <br><br>Posibles sintomas:
                    <br><br>
                    <ul style="text-align: justify;">
                        <li>
                            Problemas al orinar, incluyendo un flujo urinario lento o debilitado o necesidad de orinar con más frecuencia, especialmente de noche
                        </li>
                        <br>
                        <li>
                            Sangre en la orina o en el semen
                        </li>
                        <br>
                        <li>
                            Dificultad para lograr una erección (disfunción eréctil)
                        </li>
                        <br>
                        <li>
                            Dolor en las caderas, la espalda (columna vertebral), el tórax (costillas) u otras áreas, (puede deberse a que el cáncer se ha propagado a los huesos)
                        </li>
                        <br>
                        <li>
                            Debilidad o adormecimiento de las piernas o los pies, o incluso pérdida del control de la vejiga o los intestinos debido a que el cáncer comprime la médula espinal.
                        </li>
                    </ul>
                </p>
            </th>
        </tr>
    </tbody>
</table>
{% endblock contenido %}